// <auto-generated />
using Lab09.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab09.Migrations
{
    [DbContext(typeof(vdlDbContext))]
    partial class vdlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lab09.Models.vdlLoaiSanPham", b =>
                {
                    b.Property<long>("vdlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("vdlId"));

                    b.Property<string>("vdlMaLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vdlTenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("vdlTrangThai")
                        .HasColumnType("bit");

                    b.HasKey("vdlId");

                    b.ToTable("vdl_LoaiSanPham");
                });

            modelBuilder.Entity("Lab09.Models.vdlSanPham", b =>
                {
                    b.Property<long>("vdlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("vdlId"));

                    b.Property<decimal>("vdlDonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("vdlHinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("vdlLoaiId")
                        .HasColumnType("bigint");

                    b.Property<string>("vdlMaSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("vdlSoLuong")
                        .HasColumnType("int");

                    b.Property<string>("vdlTenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("vdlId");

                    b.HasIndex("vdlLoaiId");

                    b.ToTable("vdl_SanPham");
                });

            modelBuilder.Entity("Lab09.Models.vdlSanPham", b =>
                {
                    b.HasOne("Lab09.Models.vdlLoaiSanPham", "LoaiSanPham")
                        .WithMany("SanPhams")
                        .HasForeignKey("vdlLoaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiSanPham");
                });

            modelBuilder.Entity("Lab09.Models.vdlLoaiSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
